=== Jean-Baptiste-Camps/FoPhil-Neuchatel/03_DTD/03_DTD_exemple/exp_03_DTDExterne/film.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT film (title,casting)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT casting (director,actor+)>
<!ELEMENT director (firstName,lastName)>
<!ELEMENT firstName (#PCDATA)>
<!ELEMENT lastName (#PCDATA)>
<!ELEMENT actor (#PCDATA)>

=== Jean-Baptiste-Camps/FoPhil-Neuchatel/03_DTD/03_DTD_exemple/exp_03_DTDExterne/filmDTDexterne.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE film SYSTEM "film.dtd">

<film>
    <title>Raiders of the Lost Ark</title>
    <casting>
        <director>
            <firstName>Steven</firstName>
            <lastName>Spielberg</lastName>
        </director>
        <actor>
            Harrison Ford
        </actor>
        <actor>
            Karen Allen
        </actor>
    </casting>
</film>
